### ISSUE TITLE
Fade out help-items

### ISSUE THREAD

**Issue by hakloev** [Bergalerga/Millionairedinjo#3]
Help-items should be faded to 0.3-ish when they are used. 

``` css
#help-X {
    opacity: 0.3;
}
```
